<?xml version="1.0" encoding="utf-8"?><Database Name="CoffeeDB" Class="CoffeeDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-1GNCEEN\SQLEXPRESS;Initial Catalog=CoffeeDB;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="CoffeeManagement.Properties.Settings" SettingsPropertyName="CoffeeDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Coffee" Member="Coffees">
    <Type Name="Coffee">
      <Column Name="CoffeeID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CoffeeName" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ImageName" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>